### ISSUE TITLE
Create simplistic Japan Region in TIMES

### ISSUE THREAD

**Issue by katyhuff** [arfc/i2cner#14]
- [x] Create a region called Japan with approximately Japan's current electricity consumption.
- [x] Have electricity demand increase 1% per year for 100 years
- [x] Answer that demand with just one type of generation (coal? nuclear? wind? whatever.)

**Comment by achubbz** [comment]
@katyhuff Model working. Modified slightly by using two types of power sources(expensive, exhaustible vs cheap, abundant) to check if VEDA-BE was yielding sensible results. 

Everything seems to be in working order. Results make sense. Ready to demonstrate in person.

**Comment by katyhuff** [comment]
Exciting. I'd love to see it. Perhaps our meeting wednesday is a good time to discuss/demo this.
