### ISSUE TITLE
Create a Virtual Machine

### ISSUE THREAD

**Issue by katyhuff** [arfc/I2CNER#3]
This issue can begin when #2 is complete. You can use virtual box to create a virtual machine. 

- [x] Open virtualbox 
- [x] Create a new windows virtual machine, with significant memory and storage, name it something informative (times?)
- [x] Use the windows .iso file to install an operating system to your machine
- [x] Select a username and password that are generic and can be shared (e.g. arfc/arfc or i2cner/i2cner)
- [x] Once you have a clean windows VM, save the machine state, so that you can go back to that clean slate if anything gets messed up in the future.

**Comment by achubbz** [comment]
Vm name: times
Username/password: arfc
Clean state saved, vm files backed up.

**Comment by achubbz** [comment]
Windows Defender on Windows 10 S (free) and 10 Pro Education (licence obtained through UIUC Webstore) prevented installation of VEDA despite being disabled. Online fixes did not work.

Had to downgrade to Windows 8.1 (licence obtained from UIUC Webstore). VEDA installed without any problems.
Details of Windows 8.1 VM:
VM name: times_win8
Username/password: arfc
Clean state saved, vm files backed up.
