### ISSUE TITLE
Install VEDA, GAMS, and TIMES

### ISSUE THREAD

**Issue by katyhuff** [arfc/i2cner#4]
Using emails forwarded by @katyhuff, the .exe file stored on box, and the VEDA/TIMES forums online, install the dependencies of TIMES and TIMES itself on the virtual machine you created in #3. Once the installation is successful, save the machine state, so that you can go back to this fresh installation if anything gets messed up in the future.

**Comment by achubbz** [comment]
VEDA installed successfully. 

To install TIMES, need VEDA licence key, or username+password which should be available after agreement between @katyhuff  and ETSAP is approved and counter-signed by the ETSAP Operating agent.

**Comment by achubbz** [comment]
VEDA-FE fully licensed, VEDA-BE fully licensed after receiving licence keys from KanORS-EMR.
