### ISSUE TITLE
Fix absence of new renewables' capacity installation data in models

### ISSUE THREAD

**Issue by anshchaube** [arfc/i2cner#67]
To fix the absence of VarCAP/NewCAP variable in VEDA BE tables mentioned in #66 , try playing with costs:

- [x] Switch FixOM and VarOM (problem - one works for wind only, one works for solar only - no idea why, doesn't make sense)
- [x] Try adding a dummy investment cost of small magnitude to see if installed capacity is not discarded before the end of its lifetime
- [x] Try adding a more sophisticated cost structure (like nuclear) with investment and o&m costs instead of just LCoE (problem - we have future projections for LCoE only)

**Comment by achubbz** [comment]
![invcost-effect](https://user-images.githubusercontent.com/31393012/53905846-27ec5e80-400f-11e9-9dd4-0add20a87833.png)
Incorporating investment costs causes production to exceed demand for some reason.
