### ISSUE TITLE
fix issue labels

### ISSUE THREAD

**Issue by katyhuff** [arfc/i2cner#7]
This can be closed when @katyhuff has fixed the issue labels for this repo.

**Comment by achubbz** [comment]
@katyhuff I made some changes to the labels. Could you please review the current labels and give me feedback whenever possible? I'd be happy to assign myself to this issue and fix them.

**Comment by katyhuff** [comment]
I have a script that will fix them using the github api. If you don't mind waiting, I'll try to do it this weekend to all the repsitories and upload the script to a gist.

These are the ones I like: https://github.com/arfc/mlmc
