### ISSUE TITLE
Associate CO2 emissions with capacity deployment for nuclear, wind and solar

### ISSUE THREAD

**Issue by anshchaube** [arfc/i2cner#79]
This issue can be closed when CO2 emissions for the aforementioned electricity sources are tied to the construction of capacity (g CO2/kw) instead of the amount of electricity generated (gCO2 / kWh )

**Comment by achubbz** [comment]
http://forum.kanors-emr.org/showthread.php?tid=706&pid=3574&highlight=emissions+capacity#pid3574

**Comment by katyhuff** [comment]
@yanhuan0713 Can you check -- it seems to me that this must already be complete, but maybe I'm misunderstanding the goal.

**Comment by anshchaube** [comment]
This will not be incorporated as it is not a meaningful way to compare nuclear, renewables etc. with fossil fuels.
