### ISSUE TITLE
Review paper sections 1-4

### ISSUE THREAD

**Issue by anshchaube** [arfc/i2cner#95]
This issue can be closed when @Dayvis7 has reviewed the first I2CNER paper's sections 1-4, replied to this issue with a pdf that includes his comments, and @anshchaube has made all necessary suggested changes.

Please take a look at the pdf here:
https://drive.google.com/drive/folders/1LdZmdHuM9pwdLNrrd87_A5QpbL1xPj4B?usp=sharing

**Comment by Dayvis7** [comment]
[Ansh Review.pdf](https://github.com/arfc/i2cner/files/4886988/Ansh.Review.pdf)
