### ISSUE TITLE
Review paper draft

### ISSUE THREAD

**Issue by anshchaube** [arfc/i2cner#98]
[paper1.pdf](https://github.com/arfc/i2cner/files/5676216/paper1.pdf)
This issue can be closed when 

- [ ] @katyhuff  has reviewed the attached pdf.

- [ ] @anshchaube has incorporated feedback received from Prof. Huff.

**Comment by katyhuff** [comment]
Here's the current status of the review. Not complete, sorry. 
[paper-kdh-partial.pdf](https://github.com/arfc/i2cner/files/5783738/paper1.2.pdf)

**Comment by katyhuff** [comment]
All comments contained here now : 
[paper-kdh-complete.pdf](https://github.com/arfc/i2cner/files/5816712/paper1.2.pdf)
